heave_yaw:
  force:
    proportional: 6.04
    differential: 3.02
  moment:
    proportional: 0.013893
    differential: 0.00166716

lateral:
  proportional:
    x: 0.7
    y: 0.7
  differential:
    x: 0.4
    y: 0.4

pq_damping:
  roll: -0.04
  pitch: 0.04